<?php // SEARCH ?>
<?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
<script type="text/javascript">
//<![CDATA[
    var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
    searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');

    truncateOptions();
    decorateList('cart-sidebar', 'none-recursive');
    $j('document').ready(function() {
        var minicartOptions  = {
            formKey:           "<?php echo $this->getFormKey();?>"
        }
        var Mini = new Minicart(minicartOptions);
        Mini.init();
    });

</script>

<?php // TRANSLATOR ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
